# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b6f0140d4fcfc07a7528c428e94115d9aa1ebfe1433aedfb1b8713e1933a664234c05425b18a838a2cfc6ae0ef8edc534493044dce47e9704ef589b1d5bb0b4

test:
  secret_key_base: 31c19763678f3d5e11231adea1dd4e52a4c4a05b9cd0aa6ebc4d4c80477ca0928d29b1d1b7b2531747bd1db846fbb909014a6f5b8d725f35266865405dced742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1bc4efa83a485620caa371e5ede4d29718a6eead4052cd2f97a52c434f02187b2708fe1fc28361a554f37aee0e5a202f4de366d6999bfacf747b743663e92c0f
